on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 45.130.228.171
        username: u169248821.example
        password: '@Rhian12345'
        server-dir: /home/u169248821/domains/cln-backend.tech/public_html/demo/
        protocol: ftp
